"use client"

import { ArrowRight, Award, Bell, BookOpen, Check, ChevronDown, CirclePlay, Clock3, Download, ExternalLink, FileSpreadsheet, FileText, FolderOpen, GraduationCap, Hourglass, LayoutDashboard, LockKeyhole, Menu, Plus, Search, ShieldCheck, Sparkles, Star, Users, X } from "lucide-react"
import { useState } from "react"

import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import { Progress } from "@/components/ui/progress"
import { Separator } from "@/components/ui/separator"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"

export function LearnerDashboard({ onBrowse, onSignOut, notify, message }: { onBrowse: () => void; onSignOut: () => void; notify: (message: string) => void; message: string }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [section, setSection] = useState<"overview" | "courses" | "resources" | "certificates">("overview")
  return <div className="member-workspace">
    <header className="member-header"><Button variant="ghost" className="brand h-auto p-0 hover:bg-transparent" onClick={onBrowse}><span className="brand-mark"><GraduationCap /></span><span>Certi<span>Learn</span></span></Button><label className="member-search"><Search /><Input placeholder="Search your learning" /></label><div className="member-actions"><Button variant="ghost" size="icon" className="icon-btn" onClick={() => notify("You have 3 learning notifications")}><Bell /><i /></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="member-profile h-auto"><Avatar className="size-9"><AvatarFallback className="bg-emerald-100 text-[10px] font-bold text-emerald-700">AM</AvatarFallback></Avatar><div><strong>Amina Mensah</strong><small>Premium member</small></div><ChevronDown /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>My account</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem onClick={() => notify("Profile settings selected")}>Profile settings</DropdownMenuItem><DropdownMenuItem onClick={() => notify("Membership selected")}>Membership</DropdownMenuItem><DropdownMenuItem onClick={onSignOut}>Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Button variant="ghost" size="icon" className="member-menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</Button></div></header>
    <div className="dashboard-shell member-shell">
      <aside className={menuOpen ? "dashboard-sidebar member-sidebar open" : "dashboard-sidebar member-sidebar"}><div><small>MY LEARNING</small><Button variant="ghost" className={section === "overview" ? "active" : ""} onClick={() => { setSection("overview"); setMenuOpen(false); }}><LayoutDashboard /> Overview</Button><Button variant="ghost" className={section === "courses" ? "active" : ""} onClick={() => { setSection("courses"); setMenuOpen(false); }}><BookOpen /> My courses <Badge variant="secondary" className="ml-auto">4</Badge></Button><Button variant="ghost" onClick={() => notify("Continue learning selected")}><CirclePlay /> Continue learning</Button><Button variant="ghost" className={section === "resources" ? "active" : ""} onClick={() => { setSection("resources"); setMenuOpen(false); }}><FileText /> Resources</Button><Button variant="ghost" className={section === "certificates" ? "active" : ""} onClick={() => { setSection("certificates"); setMenuOpen(false); }}><Award /> Certificates <Badge variant="secondary" className="ml-auto">2</Badge></Button></div><div><small>ACCOUNT</small><Button variant="ghost" onClick={() => notify("Profile settings selected")}><Users /> Profile</Button><Button variant="ghost" onClick={() => notify("Membership selected")}><ShieldCheck /> Membership</Button><Button variant="ghost" onClick={onSignOut}><ArrowRight /> Sign out</Button></div><Card className="upgrade-card py-0"><CardContent className="p-4"><Sparkles /><strong>Premium active</strong><span>Renews Feb 18, 2027</span><Button variant="secondary" size="sm" onClick={() => notify("Membership settings opened")}>Manage plan</Button></CardContent></Card></aside>
      <section className="dashboard-content">
        {section === "overview" ? <>
        <div className="dash-title"><div><span>Sunday, July 19</span><h1>Welcome back, Amina 👋</h1><p>Keep going — you&apos;re making excellent progress.</p></div><Button className="primary-btn" onClick={onBrowse}>Browse courses <ArrowRight /></Button></div>
        <div className="stats-row"><Stat icon={<Clock3 />} value="18.5h" label="Learning time" note="+2.5h this week" /><Stat icon={<BookOpen />} value="4" label="Courses enrolled" note="2 in progress" /><Stat icon={<Award />} value="2" label="Certificates" note="1 newly earned" /><Stat icon={<Download />} value="14" label="Resources saved" note="3 this month" /></div>
        <div className="dash-grid">
          <Card className="continue-panel py-0 shadow-none"><CardContent className="p-5"><div className="panel-head"><div><h2>Continue learning</h2><p>Pick up right where you left off</p></div><Button variant="ghost" size="sm">View all <ArrowRight /></Button></div><Card className="continue-card grid py-0 shadow-none"><div className="continue-art violet"><span>DA</span><Button variant="secondary" size="icon"><CirclePlay /></Button></div><CardContent className="continue-info"><Badge variant="secondary">Data & Analytics</Badge><h3>Data Analysis with Excel</h3><p>Module 4 of 8 · Visualizing your data</p><Progress value={62} className="long-progress" /><small>62% complete <b>3h 10m left</b></small><Button size="sm" onClick={() => notify("Lesson player opened")}>Continue lesson <CirclePlay /></Button></CardContent></Card></CardContent></Card>
          <Card className="weekly-panel py-0 text-center shadow-none"><CardContent className="p-5"><div className="panel-head"><div><h2>Weekly goal</h2><p>July 13–19</p></div><Button variant="ghost" size="icon-sm">•••</Button></div><div className="goal-ring"><div><strong>3.5</strong><small>of 5 hours</small></div></div><p>You&apos;re <strong>70%</strong> there. Just 1.5 hours to go!</p><div className="week-dots">{[1,1,1,1,0,0,0].map((on,i)=><Badge variant={on ? "default" : "secondary"} key={i} className={on ? "done" : ""}>{["M","T","W","T","F","S","S"][i]}</Badge>)}</div></CardContent></Card>
          <Card className="cert-panel py-0 text-white"><CardContent className="flex w-full items-center gap-3 p-4"><div className="cert-icon"><Award /></div><div><Badge>New certificate</Badge><h3>Project Management Foundations</h3><p>Issued July 12, 2026 · ID CL-2026-1842</p></div><Button variant="outline" className="ml-auto bg-white/10 text-white" onClick={() => notify("Certificate download ready")}><span>Download</span><Download /></Button></CardContent></Card>
          <Card className="activity-panel py-0 shadow-none"><CardContent className="p-5"><div className="panel-head"><div><h2>Recent activity</h2><p>Your latest learning moments</p></div></div>{[["Completed a lesson","Creating effective project timelines","2 hours ago"],["Downloaded a resource","Risk assessment template.pdf","Yesterday"],["Earned a certificate","Project Management Foundations","July 12"]].map(([a,b,c],i)=><div className="activity" key={b}><span>{i===2?<Award />:i===1?<Download />:<Check />}</span><div><strong>{a}</strong><p>{b}</p></div><small>{c}</small></div>)}</CardContent></Card>
        </div>
        </> : section === "courses" ? <MyCourses onBrowse={onBrowse} notify={notify} /> : section === "resources" ? <MyResources notify={notify} /> : <MyCertificates notify={notify} />}
      </section>
    </div>
    {message && <div className="toast"><Check />{message}</div>}
  </div>
}

const enrolledCourses = [
  { title: "Data Analysis with Excel", category: "Data & Analytics", progress: 62, lesson: "Module 4 · Visualizing your data", time: "3h 10m left", color: "violet", code: "DA", rating: "4.8", state: "progress" },
  { title: "Effective Team Leadership", category: "Leadership", progress: 28, lesson: "Module 2 · Building team trust", time: "5h 05m left", color: "mint", code: "TL", rating: "4.8", state: "progress" },
  { title: "Project Management Foundations", category: "Leadership", progress: 100, lesson: "Completed July 12, 2026", time: "Certificate earned", color: "coral", code: "PM", rating: "4.9", state: "completed" },
  { title: "Workplace Health & Safety", category: "Compliance", progress: 100, lesson: "Completed June 24, 2026", time: "Certificate earned", color: "gold", code: "HS", rating: "4.9", state: "completed" },
] as const

function MyCourses({ onBrowse, notify }: { onBrowse: () => void; notify: (message: string) => void }) {
  const [filter, setFilter] = useState<"all" | "progress" | "completed">("all")
  const visible = filter === "all" ? enrolledCourses : enrolledCourses.filter(course => course.state === filter)
  return <div className="my-courses-view">
    <div className="member-section-title"><div><span>MY LEARNING</span><h1>My courses</h1><p>Continue learning, revisit completed training, and track your progress.</p></div><Button className="primary-btn" onClick={onBrowse}>Explore more courses <ArrowRight /></Button></div>
    <div className="course-summary"><Card><CardContent><BookOpen /><span><strong>4</strong><small>Total courses</small></span></CardContent></Card><Card><CardContent><CirclePlay /><span><strong>2</strong><small>In progress</small></span></CardContent></Card><Card><CardContent><Award /><span><strong>2</strong><small>Completed</small></span></CardContent></Card><Card><CardContent><Clock3 /><span><strong>11.5h</strong><small>Learning time</small></span></CardContent></Card></div>
    <div className="course-filter-row"><div>{(["all","progress","completed"] as const).map(item => <Button variant={filter === item ? "default" : "ghost"} size="sm" key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item === "all" ? "All courses" : item === "progress" ? "In progress" : "Completed"}</Button>)}</div><label><Search /><Input placeholder="Search enrolled courses" /></label></div>
    <div className="enrolled-grid">{visible.map(course => <Card className="enrolled-card py-0 shadow-none" key={course.title}><div className={`enrolled-art ${course.color}`}><span>{course.code}</span>{course.state === "completed" ? <i><Check /></i> : <Button variant="secondary" size="icon" onClick={() => notify(`${course.title} lesson opened`)}><CirclePlay /></Button>}</div><CardContent className="enrolled-copy"><div className="enrolled-category"><Badge variant="secondary">{course.category}</Badge><b><Star fill="currentColor" />{course.rating}</b></div><h2>{course.title}</h2><p>{course.lesson}</p><div className="enrolled-progress"><Progress value={course.progress} /><span>{course.progress}%</span></div><Separator /><div className="enrolled-bottom"><small>{course.time}</small><Button variant="ghost" size="sm" onClick={() => notify(course.state === "completed" ? `${course.title} review opened` : `${course.title} continued`)}>{course.state === "completed" ? "Review course" : "Continue"}<ArrowRight /></Button></div></CardContent></Card>)}</div>
  </div>
}

function MyCertificates({ notify }: { notify: (message: string) => void }) {
  return <div className="certificates-view">
    <div className="member-section-title"><div><span>MY CREDENTIALS</span><h1>Certificates</h1><p>Manage your earned credentials and request certificates for eligible courses.</p></div><Button className="primary-btn" onClick={() => notify("Certificate request form opened")}><Plus /> Request certificate</Button></div>
    <div className="certificate-stats"><CertificateMetric icon={<Award />} tone="earned" value="2" label="Certificates earned" note="Both active and verified" /><CertificateMetric icon={<Hourglass />} tone="review" value="1" label="Under review" note="Usually completed in 2–3 days" /><CertificateMetric icon={<Check />} tone="eligible" value="1" label="Eligible to request" note="Course requirements completed" /></div>
    <Card className="issued-section py-0 shadow-none"><CardContent className="p-5"><div className="certificate-heading"><div><h2>Issued certificates</h2><p>Your downloadable and publicly verifiable credentials</p></div><Button variant="ghost" size="sm" onClick={() => notify("Public verification page opened")}>How verification works <ExternalLink /></Button></div><div className="issued-grid"><IssuedCertificate title="Project Management Foundations" id="CL-2026-1842" date="July 12, 2026" accent="emerald" notify={notify} /><IssuedCertificate title="Workplace Health & Safety" id="CL-2026-0914" date="June 24, 2026" accent="amber" notify={notify} /></div></CardContent></Card>
    <div className="certificate-status-grid"><Card className="status-card review-card py-0 shadow-none"><CardContent className="flex w-full items-center gap-3 p-4"><span><Hourglass /></span><div><Badge variant="secondary">Under review</Badge><h3>Data Analysis with Excel</h3><p>Requested July 18, 2026 · Your course completion and final assessment are being reviewed.</p><Progress value={66} className="mt-3" /><b>Submitted <em>Under review</em> Decision</b></div><Button variant="outline" size="sm" onClick={() => notify("Certificate request details opened")}>View request</Button></CardContent></Card><Card className="status-card eligible-card py-0 shadow-none"><CardContent className="flex w-full items-center gap-3 p-4"><span><Check /></span><div><Badge variant="secondary">You&apos;re eligible</Badge><h3>Effective Team Leadership</h3><p>You completed all 28 lessons. Submit a request to receive your verified certificate.</p></div><Button size="sm" onClick={() => notify("Certificate request started")}>Request now <ArrowRight /></Button></CardContent></Card></div>
  </div>
}

const resources = [
  { title: "Project charter template", course: "Project Management Foundations", type: "PDF", size: "1.2 MB", category: "Templates", downloads: 1842, premium: false, icon: "pdf" },
  { title: "Risk assessment worksheet", course: "Project Management Foundations", type: "XLSX", size: "86 KB", category: "Worksheets", downloads: 1276, premium: true, icon: "sheet" },
  { title: "Excel formulas quick reference", course: "Data Analysis with Excel", type: "PDF", size: "2.4 MB", category: "Guides", downloads: 2319, premium: true, icon: "pdf" },
  { title: "Leadership conversation planner", course: "Effective Team Leadership", type: "DOCX", size: "140 KB", category: "Templates", downloads: 906, premium: true, icon: "doc" },
  { title: "Workplace safety checklist", course: "Workplace Health & Safety", type: "PDF", size: "940 KB", category: "Checklists", downloads: 3054, premium: false, icon: "pdf" },
  { title: "Team performance scorecard", course: "Effective Team Leadership", type: "XLSX", size: "112 KB", category: "Worksheets", downloads: 774, premium: true, icon: "sheet" },
] as const

function MyResources({ notify }: { notify: (message: string) => void }) {
  const [filter, setFilter] = useState("All resources")
  const [query, setQuery] = useState("")
  const categories = ["All resources", "Templates", "Guides", "Worksheets", "Checklists"]
  const visible = resources.filter(resource => (filter === "All resources" || resource.category === filter) && resource.title.toLowerCase().includes(query.toLowerCase()))
  return <div className="resources-view">
    <div className="member-section-title"><div><span>LEARNING LIBRARY</span><h1>Resources & downloads</h1><p>Practical templates, guides, and tools included with your courses.</p></div><Button className="primary-btn" onClick={() => notify("Downloaded files view opened")}><FolderOpen /> My downloads</Button></div>
    <Card className="resource-highlight border-0 py-0 text-white"><CardContent className="flex w-full items-center justify-between gap-6 p-6"><div><span><Sparkles /></span><div><Badge>Premium library</Badge><h2>Everything you need, ready to use</h2><p>Your active membership unlocks every premium resource in the learning library.</p></div></div><Separator orientation="vertical" className="h-12 bg-white/10" /><div><strong>48</strong><span>Premium resources<small>across 12 categories</small></span></div></CardContent></Card>
    <div className="resource-toolbar"><div>{categories.map(category => <Button variant={filter === category ? "default" : "ghost"} size="sm" key={category} className={filter === category ? "active" : ""} onClick={() => setFilter(category)}>{category}</Button>)}</div><label><Search /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search resources" /></label></div>
    <Card className="resource-table overflow-hidden py-0 shadow-none"><Table><TableHeader><TableRow><TableHead>Resource</TableHead><TableHead>Course</TableHead><TableHead>File</TableHead><TableHead>Access</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{visible.map(resource => <TableRow key={resource.title}><TableCell><div className="flex items-center gap-3"><span className={`file-kind ${resource.icon}`}>{resource.icon === "sheet" ? <FileSpreadsheet /> : <FileText />}</span><div className="resource-name"><strong>{resource.title}</strong><small>{resource.category} · {resource.downloads.toLocaleString()} downloads</small></div></div></TableCell><TableCell><div className="resource-course"><BookOpen /><span>{resource.course}</span></div></TableCell><TableCell><div className="resource-file"><strong>{resource.type}</strong><small>{resource.size}</small></div></TableCell><TableCell><Badge variant={resource.premium ? "secondary" : "outline"} className={resource.premium ? "access premium" : "access free"}>{resource.premium ? <><LockKeyhole /> Premium</> : <>Free</>}</Badge></TableCell><TableCell className="text-right"><Button variant="outline" size="sm" className="download-action" onClick={() => notify(`${resource.title} download ready`)}><Download /><span>Download</span></Button></TableCell></TableRow>)}{visible.length === 0 && <TableRow><TableCell colSpan={5}><div className="resource-empty"><Search /><strong>No resources found</strong><p>Try another search or category.</p></div></TableCell></TableRow>}</TableBody></Table></Card>
    <Card className="download-note py-0 shadow-none"><CardContent className="flex w-full items-center gap-3 p-3"><ShieldCheck /><div><strong>Secure downloads</strong><p>Resource links in the production platform will be private and expire automatically.</p></div><Button variant="ghost" size="sm" onClick={() => notify("Download history opened")}>View download history <ArrowRight /></Button></CardContent></Card>
  </div>
}

function IssuedCertificate({ title, id, date, accent, notify }: { title: string; id: string; date: string; accent: "emerald" | "amber"; notify: (message: string) => void }) {
  return <Card className={`issued-certificate ${accent} py-0 shadow-none`}><div className="certificate-paper"><div className="cert-brand"><span><GraduationCap /></span><strong>CertiLearn</strong></div><small>CERTIFICATE OF COMPLETION</small><p>This certifies that</p><h3>Amina Mensah</h3><i /><b>{title}</b><footer><span>ISSUED<br /><strong>{date}</strong></span><Award /><span>CREDENTIAL ID<br /><strong>{id}</strong></span></footer></div><CardContent className="certificate-card-copy"><div><Badge className="active-badge"><ShieldCheck /> Active</Badge><h2>{title}</h2><p>Issued {date} · No expiration</p></div><div><Button size="sm" onClick={() => notify(`${title} download ready`)}><Download /> Download PDF</Button><Button variant="outline" size="sm" onClick={() => notify(`${id} verification opened`)}><ExternalLink /> Verify</Button></div></CardContent></Card>
}

function CertificateMetric({ icon, tone, value, label, note }: { icon: React.ReactNode; tone: string; value: string; label: string; note: string }) {
  return <Card className="py-0 shadow-none"><CardContent className="flex items-center gap-3 p-4"><span className={tone}>{icon}</span><div><strong>{value}</strong><p>{label}</p><small>{note}</small></div></CardContent></Card>
}

function Stat({ icon, value, label, note }: { icon: React.ReactNode; value: string; label: string; note: string }) {
  return <Card className="stat-card py-0 shadow-none"><CardContent className="flex items-center gap-3 p-4"><span>{icon}</span><div><strong>{value}</strong><p>{label}</p><small>{note}</small></div></CardContent></Card>
}
